<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="abstractrefs" nsURI="http://www.example.org/abstractrefs" nsPrefix="abstractrefs">
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractItem" eType="#//AbstractItem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interfaceItem" eType="#//InterfaceItem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concreteItem" eType="#//ConcreteItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unchangeableItem" eType="#//ConcreteItem" changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractItem" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfaceItem" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
