<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="base" nsPrefix="base">
    <eClassifiers xsi:type="ecore:EClass" name="Root">
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
          containment="true" eType="#/0/Item"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Item" abstract="true"/>
  </ecore:EPackage>
  <ecore:EPackage name="types" nsURI="   " nsPrefix="types">
    <eClassifiers xsi:type="ecore:EClass" name="First" eSuperTypes="#/0/Item"/>
    <eClassifiers xsi:type="ecore:EClass" name="Second" eSuperTypes="#/0/Item"/>
  </ecore:EPackage>
</xmi:XMI>
